[pytest]
# Diz ao pytest onde está o código fonte
pythonpath = src

# Padrão de arquivos de teste
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Diretório de testes
testpaths = tests

# Mostrar prints durante testes
addopts = 
    -v
    --tb=short
    --cov=educalin
    --cov-report=html
    --cov-report=term-missing